GEO_DEMO_RN = [
    "TotPop",  # "Total Population"
    "TotPopOccUnits",  # "Total population in occupied housing units"
    "TotNumOwnOccUnit",  # "Total number of owner occupied units"
    "TotNumRentOccUnit",  # "Total number of renter occupied units"
    "PopLTHSDip",  # "Population with less than a high school diploma"
    "PopHSDip",  # "Population with high school diploma or equivalent"
    "PopAssoc",  # "Population with some college/associates degree"
    "PopBA",  # "Population with bachelors degree"
    "PopGrad",  # "Population with a graduate degree"
    "PopIncLT10",  # "Population with income less than 9999"
    "PopInc1015",  # "Population with income between 10000 and 14999"
    "PopInc1525",  # "Population with income between 15000 and 24999"
    "PopInc2535",  # "Population with income between 25000 and 34999"
    "PopInc3550",  # "Population with income between 35000 and 49999"
    "PopInc5065",  # "Population with income between 50000 and 64999"
    "PopInc6575",  # "Population with income between 65000 and 74999"
    "PopIncGT75",  # "Population with income of 75000 or more"
    "UnempPop",  # "Population in labor force and unemployed"
    "RetPop",  # "Population that is retired with retirement income"
    "RetPopNoRetInc",  # "Retired without retirement income"
    "PopBlwPovLvl",  # "Population with income below poverty level in past 12 months"
]
